### ISSUE TITLE
`bootc install to-disk --via-loopback` failed at least once for me

### ISSUE THREAD

**Issue by mvo5** [containers/bootc#356] opened 2024-02-20 12:02 UTC
When using `bootc install to-disk --via-loopback`  on fedora-39 I got the following error:

```
$ sudo  podman run --pull=newer --rm --privileged --pid=host -e BOOTC_SKIP_SELINUX_HOST_CHECK=true -v $(pwd):/output -v /var/lib/containers:/var/lib/containers --security-opt label=type:unconfined_t quay.io/centos-bootc/fedora-bootc:eln bootc install to-disk --via-loopback /output/bootc-install-to-disk.img
Automatically enabling --generic-image when installing via loopback
Mounting tmpfs /tmp
Mounting efivarfs /sys/firmware/efi/efivars
Host kernel does not have SELinux support, but target enables it by default; BOOTC_SKIP_SELINUX_HOST_CHECK is set, continuing anyways
losetup: /output/bootc-install-to-disk.img: failed to set up loop device: No such file or directory
losetup: device node /dev/loop1 (7:1) is lost. You may use mknod(1) to recover it.
ERROR Installing to disk: Task losetup failed: ExitStatus(unix_wait_status(256))
```

Re-running it fixed it. This may not be actionable as it's unclear how hard/easy it is to reproduce but I wanted to report it for awareness.

**Comment by jeckersb** [comment] 2024-02-20 19:53
I'm going to close this as a duplicate of #352, but thanks for confirming that you were able to reproduce it at least once, that's very helpful to know!

**Closed by jeckersb** 2024-02-20 19:53 UTC
